### ISSUE TITLE
AMD RX 560/Windows 10: error at device layer extension during trying to submit report

### ISSUE THREAD

**Issue by Andreyogld3d** [SaschaWillems/VulkanCapsViewer#100]
Hi @SaschaWillems, 

![image](https://user-images.githubusercontent.com/8597425/99804553-3a445e00-2b4c-11eb-906f-b331496933cf.png)

@SaschaWillems I could help to fix this error, but I cannot compile project:

**1>------ Build started: Project: vulkanCapsViewer, Configuration: Release x64 ------
1>Moc'ing vulkancapsviewer.h...
1>The system cannot find the path specified.
1>Uic'ing vulkancapsviewer.ui...
1>The system cannot find the path specified.
1>Moc'ing submitDialog.h...
1>The system cannot find the path specified.
1>Moc'ing vulkandatabase.h...
1>The system cannot find the path specified.
1>Moc'ing settingsDialog.h...
1>The system cannot find the path specified.
1>Rcc'ing vulkancapsviewer.qrc...
1>The system cannot find the path specified.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 3.
1>Done building project "vulkanCapsViewer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========**

**Comment by SaschaWillems** [comment]
That's a server side error, and nothing that could be fixed in the Vulkan Caps Viewer itself. Can attach the report to this issue, so I can check what went wrong?

**Comment by Andreyogld3d** [comment]
@SaschaWillems [I attached report](https://github.com/SaschaWillems/VulkanCapsViewer/files/5580154/vulkanreport.zip)

**Comment by SaschaWillems** [comment]
Can you try uploading without `VK_LAYER_LUNARG_override`? Afaik that layer comes from the Vulkan configurator, and may cause the upload error.

**Comment by Andreyogld3d** [comment]
@SaschaWillems 
>Afaik that layer comes from the Vulkan configurator, and may cause the upload error.
You are absolutly right! new report has been uploade succesfully, You may fix issue or close as you wish.
