### ISSUE TITLE
Bad alternating row color with dark theme in 3.0

### ISSUE THREAD

**Issue by zeitt** [SaschaWillems/VulkanCapsViewer#107]
Hello,
I noticed that 3.0 version seems to have white background and white text on every other row, when using Dark theme. This makes reading those rows impossible. Older version (2.2) still works correctly.

Manjaro Linux, X11, KDE 5.20, Theme: Breeze **Dark**.

![image](https://user-images.githubusercontent.com/733579/104125098-40d99f80-535d-11eb-902e-15c40beda330.png)

**Comment by SaschaWillems** [comment]
Thanks for raising this issue. I have overriden the default alternating row color as it was too dark on the light theme. Looks like I forgot to take dark themes into account.
