### ISSUE TITLE
The "Supports presentation" is false for graphics queue family.

### ISSUE THREAD

**Issue by jjoganic** [SaschaWillems/VulkanCapsViewer#120]
This may just be a display issue, or perhaps I'm misunderstanding how this is calculated, but none of the queue families shows true for "Supports Presentation", including queue 0 which has the GRAPHICS_BIT for my Nvidia GTX 1080Ti.  Version is 3.01.

**Comment by SaschaWillems** [comment]
What operating system? It's not properly working on Linux, but should work fine on Windows.

**Comment by jjoganic** [comment]
It is in fact Linux running the vulkancapsviewer_3.01_linux64.AppImage.

**Comment by jjoganic** [comment]
Since the data in the gpuinfo database now shows it incorrectly, it might be worth tweaking that value on the server-side.  I don't suppose it will allow re-uploading when the issue is resolved.

**Comment by SaschaWillems** [comment]
While there is some kind of update mechanism, it's not able to handle changes in single fields. So no, there's no way of updating the report from the client application once this is finished. I tried several times to fix this, but never got it to actually work on my Linux devices. I'll give it another shot and see if I can fix this.
