### ISSUE TITLE
Android Play Store versions post v1.92 incompatible with Samsung SM-T580

### ISSUE THREAD

**Issue by eloj** [SaschaWillems/VulkanCapsViewer#126]
This isn't exactly a new issue, but anyway; My Samsung SM-T580 (aka Galaxy Tab A 10.1) tablet has v1.92 installed from the Play Store, but it can not take new versions. Clicking 'Install' on the store shows "This item is not compatible with your device".

The installed version still runs of couse, and I have previously submitted [report 4437](https://vulkan.gpuinfo.org/displayreport.php?id=4437) from it.

I don't really know Android development, but nothing obvious stood out in the manifest. Unless device compatibility is dictated by `minSdkVersion`?

Not the end of the world, just wanted to make sure this isn't just an oversight.

**Comment by SaschaWillems** [comment]
Google regularly increases the `minSdkVersion` requirement for app updates, which dictates what devices the app will be available on. There's nothing I can do about this. If I don't increase this, I can't release an update to the store. Feel free to download the apk from the [downloads section](https://vulkan.gpuinfo.org/download.php) though and install it using side loading.

**Comment by eloj** [comment]
Alright, that seems like a positively terrible way to run an app store.
