### ISSUE TITLE
Trouble installing apk on Android

### ISSUE THREAD

**Issue by krOoze** [SaschaWillems/VulkanCapsViewer#129]
I have trouble installing tha apk on Android 7 phone (armeabi-v7a).

On  attempt at installing, it just says there was an uspecified error during package validation.

**Comment by SaschaWillems** [comment]
Android 7 is too old. I have to regularly increase the min requirements for Android min. and target SDK so I can release it in the store. It's a requirement by google. Currently it's API v26 which is Android 8.0.

If you compile the apk with a lower min SDK requirement it may work on 7.0.

**Comment by krOoze** [comment]
I think store does not require min version, just target version.

**Comment by krOoze** [comment]
Readme says Qt 5.8 as a dependency. I tried 5.9 (earliest Qt installer offers) and that wont compile because of `setRecursiveFilteringEnabled` that apparently was introduced in 5.10. Qt 6 won't compile because something was deprecated. Had problem with other versions where it seems I get blank screen with only the title bar.

**Comment by SaschaWillems** [comment]
Looks like I need to update the Readme. Haven't tested with Qt 6 yet, but Qt 5.12 should work.

**Comment by krOoze** [comment]
[Seems to work](https://github.com/krOoze/VulkanCapsViewer/releases/tag/3.02). Thanks.

Still weird though that store would not allow it. There seem to be a requirement for `targetSdkVersion`, not `min`.

**Comment by SaschaWillems** [comment]
That's very well possible. I haven't checked that yet.

**Comment by SaschaWillems** [comment]
I have lowered min. api level to 24 (Android 7.0).

**Comment by krOoze** [comment]
@SaschaWillems Still won't install though. :/ Possibly wrong ABI? You might want to add `armeabi-v7a`. Or have it as a sole target, as all the arm64 will support it anyway.

**Comment by SaschaWillems** [comment]
Yeah, forgot about that. I have dropped support from armeabi-v7a some time ago. Will have to look at adding back a separate build target.
