### ISSUE TITLE
Database doesn't get updated or client wrongly displays entry as updatable.

### ISSUE THREAD

**Issue by spnda** [SaschaWillems/VulkanCapsViewer#131]
The database doesn't get updated and in the message it also displays that nothing was updated, yet always prompts me that I can update the database entry.
![image](https://user-images.githubusercontent.com/43609023/138584619-9fbdf886-8d9a-48d7-b3d0-9f577adc1c5c.png)

The JSON file is (in a zip cuz GH doesn't support it?) attached here:
[NVIDIA GeForce RTX 2080.zip](https://github.com/SaschaWillems/VulkanCapsViewer/files/7404248/NVIDIA.GeForce.RTX.2080.zip)

**Comment by SaschaWillems** [comment]
Does this happen with different driver versions too? While debugging this, I noticed that your report has different extensions to what is stored for that gpu + driver version in the database.

**Comment by spnda** [comment]
I'm on 472.55 right now with caps viewer 3.04 and it just shows "Device is already present in the databse" (I uploaded this specific entry though). This only happened specifically on that driver version (I was changing driver versions quite frequently and never noticed this with any other version) and as you said on Discord, the existing entry was probably uploaded with an outdated version of caps viewer, thus missing some extensions/properties.

**Comment by SaschaWillems** [comment]
Thanks for the info. I'll close this then. If it happens again with a recent driver and a recent version of the caps viewer, feel free to repoen the issue.

**Comment by SaschaWillems** [comment]
Thanks for the update. Can you save the report to disk and attach the json to this issue?

**Comment by spnda** [comment]
Because JSON is still not supported on github....
https://gist.github.com/spnda/580efbfec0f6cf49dd5d667107fa82c9

**Comment by SaschaWillems** [comment]
Thanks. I think I found the root cause for this. Oddly your report does have more extensions than the original report, even though both are using the same driver version. I'll need to investigate that a bit further.

**Comment by spnda** [comment]
> Thanks. I think I found the root cause for this. Oddly your report does have more extensions than the original report, even though both are using the same driver version. I'll need to investigate that a bit further.

That's because they were using VCV 3.01. There's been many extensions added since and a lot of them are supported in recent drivers, but won't show up in the report with an outdated viewer.

**Comment by SaschaWillems** [comment]
No, that's not the cause. Old and new versions will report the same extension list. What newer versions of the tool add, is extended data for newer extensions (e.g. values and limits for that extension). That's what needs to be updated.

But the report you try to update is actually missing two extensions that your report has, which should never be the case for the same driver version.

**Comment by SaschaWillems** [comment]
@spnda : Can you check again? I pushed a fix to the back-end.

**Comment by spnda** [comment]
@SaschaWillems Yes, it works now. See my update on https://vulkan.gpuinfo.org/displayreport.php?id=13279. Thanks!
