### ISSUE TITLE
Report from Windows 11 is marked as Windows 10

### ISSUE THREAD

**Issue by suratovvlad** [SaschaWillems/VulkanCapsViewer#132]
I submitted report from Windows 11, however in the database it shows that platform is Windows 10

![image](https://user-images.githubusercontent.com/3812290/139324127-ac69da77-3b77-43a4-a5d3-5d5e5268dd1c.png)

![image](https://user-images.githubusercontent.com/3812290/139323987-7021f9f6-4c91-4754-8a4d-30f3c0e2a002.png)

**Comment by SaschaWillems** [comment]
This has been fixed with version 3.26.
