### ISSUE TITLE
Version going backwards: 3.05 > 3.1

### ISSUE THREAD

**Issue by jbeich** [SaschaWillems/VulkanCapsViewer#134]
[Repology](https://repology.org/project/vulkan-caps-viewer/versions) and [FreeBSD pkg](https://man.freebsd.org/pkg-version/8) treat 3.1 release as older due to leading 0 (zero). Maybe 3.1 should be re-tagged as 3.10.

```
$ pkg version -t 3.05 3.1
>

$ pkg version -t 3.05 3.10
<
```

**Comment by SaschaWillems** [comment]
Where are those packages coming from? I'm not the maintainer of those and wasn't aware of something like this. If versioning is problematic, I'll fix it with the next release.

**Comment by SaschaWillems** [comment]
Just published 3.11 as a minor bugfix.
