### ISSUE TITLE
Show error message when MoltenVK is not installed

### ISSUE THREAD

**Issue by janekb04** [SaschaWillems/VulkanCapsViewer#135]
Currently, when the app is ran on macOS (version 12.1, M1 Pro) without MoltenVK installed, it crashes with no error message:

<img width="1112" alt="Screenshot 2022-02-05 at 14 13 15" src="https://user-images.githubusercontent.com/13035076/152643606-d12d7b52-6950-47cc-a9b9-56af72dcdb42.png">

The reason is outlined in the error log, but it can be hard to notice for a first time user. I think the app should display a message box saying that MoltenVK was not installed, similar to:

<img width="372" alt="Screenshot 2022-02-05 at 14 17 12" src="https://user-images.githubusercontent.com/13035076/152643740-7b587522-1ef8-4b86-9327-3b8ba0ebd476.png">

Performing the installation of MoltenVK is probably out of scope, so the button could simply redirect to the [LunarG website](https://www.lunarg.com/vulkan-sdk/).

**Comment by GainLee** [comment]
It's hard to notice and I meet that too. I come back to read README.md again and found the dependencies message at the bottom.

**Comment by SaschaWillems** [comment]
I don't own a Mac to develop or test this. So a PR to add this would be very much appreciated.

**Comment by mizvekov** [comment]
There are two issues I see here:

* If one wishes to diagnose a missing vulkan implementation, then we can't link to the shared vulkan library at compile time, we need to `dlopen` it. This is not a MacOS specific problem, and I expect this issue will exist in all platforms.
* MacOS bundles are supposed to pack all of their dependencies, everything besides system / vendor provided shared libraries needs to be there. MacOS doesn't have a vendor provided package manager, and you can't specify dependencies between bundles. Right now this bundle silently depends on another (VulkanSDK) being installed, and for example it's incompatible with the loader / MoltenVK provided through homebrew, as they are installed in different paths. Bundling is however not ideal for vulkancapsviwer, I think. It would make more sense that this would be provided by a package manager like homebrew or macports, but this applies to the VulkanSDK as well.

**Comment by SaschaWillems** [comment]
As noted above, I don't have a Mac to implement/test this.
