### ISSUE TITLE
build vulkancapsviewer as dual display platform in linux

### ISSUE THREAD

**Issue by sl1pkn07** [SaschaWillems/VulkanCapsViewer#136]
Hi

right now, when build on linux, you need specify if you use Xorg/X11 ( ` DEFINES+=X11`) display platform  or wayland (` DEFINES+=WAYLAND`) display platform

is possible make the program dual interface and depending in what display platform is launched, use one or other?

greetings

**Comment by SaschaWillems** [comment]
I don't know enough about linux to really do anything with that regards, but I thought this was actually already possible, see https://github.com/SaschaWillems/VulkanCapsViewer/pull/91.

**Comment by sl1pkn07** [comment]
ok. then I have misunderstood this https://aur.archlinux.org/packages?O=0&SeB=nd&K=vulkan-caps&outdated=&SB=n&SO=a&PP=250&submit=Go (separate the packages in the two flavours)

sorry the noise
