### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by GainLee** [SaschaWillems/VulkanCapsViewer#139]
The app shows a empty view and there are some logs for it.

02-19 20:45:24.435  2818  2818 E Qt      : Can't create main activity
02-19 20:45:24.435  2818  2818 E Qt      : android.content.res.Resources$NotFoundException: String array resource ID #0x0
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.content.res.Resources.getStringArray(Resources.java:691)
02-19 20:45:24.435  2818  2818 E Qt      : 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:423)
02-19 20:45:24.435  2818  2818 E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivityLoader.onCreate(QtActivityLoader.java:166)
02-19 20:45:24.435  2818  2818 E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreateHook(QtActivity.java:267)
02-19 20:45:24.435  2818  2818 E Qt      : 	at org.qtproject.qt5.android.bindings.QtActivity.onCreate(QtActivity.java:274)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.Activity.performCreate(Activity.java:8006)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.Activity.performCreate(Activity.java:7990)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1317)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3471)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3662)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2117)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.os.Looper.loop(Looper.java:223)
02-19 20:45:24.435  2818  2818 E Qt      : 	at android.app.ActivityThread.main(ActivityThread.java:7866)
02-19 20:45:24.435  2818  2818 E Qt      : 	at java.lang.reflect.Method.invoke(Native Method)
02-19 20:45:24.435  2818  2818 E Qt      : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-19 20:45:24.435  2818  2818 E Qt      : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by SaschaWillems** [comment]
The one form the playstore or the one from the download link of the database? Or one you built yourself? I had to update to a newer Qt version and that broke a lot of things, so I had to redo some Android build files. But it worked fine for me.

**Comment by GainLee** [comment]
> The one form the playstore or the one from the download link of the database? Or one you built yourself? I had to update to a newer Qt version and that broke a lot of things, so I had to redo some Android build files. But it worked fine for me.

I download from blow link
https://vulkan.gpuinfo.org/downloads/vulkancapsviewer_3.2_arm.apk

**Comment by SaschaWillems** [comment]
Please redownload and test again. It looks like Android builds are completely broken with the Qt version I updated too and only debug builds will show anything. Had to rebuild a debug apk and replaced the download with that. Doing native stuff on Android is just an unpleasant experience :(

**Comment by GainLee** [comment]
> Please redownload and test again. It looks like Android builds are completely broken with the Qt version I updated too and only debug builds will show anything. Had to rebuild a debug apk and replaced the download with that. Doing native stuff on Android is just an unpleasant experience :(

The new apk works well. I'm coding Vulkan on android, I know that unpleasant experience, lol
