### ISSUE TITLE
AppImage newer than 3.11 segfaults with mesa-git (Debian sid)

### ISSUE THREAD

**Issue by dpanter** [SaschaWillems/VulkanCapsViewer#143]
Tried every AppImage from 3.05 up to both 3.21 versions. All versions newer than 3.11 segfault.

Using Siduction (Debian sid based), KDE Wayland 5.24.5, kernel 5.18-rc5, mesa-git 22.2 built today. Also tested with kernel 5.17 and mesa-git 22.1 (llvm13) from a month ago.
System specs, inxi -b  https://pastebin.com/fubP7s3M

QT_DEBUG_PLUGINS=1, AppImage 3.11 (works)  https://pastebin.com/qwJ40k1G

QT_DEBUG_PLUGINS=1, AppImage 3.2 (segfault)  https://pastebin.com/7JFbTpKS
GDB backtrace, AppImage 3.2  https://pastebin.com/pGmCmA7b

**Comment by SaschaWillems** [comment]
I probably won't be able to help here as I don't use Debian. But you can please run the app with a debugger attached (e.g. from an IDE) and paste the callstack from the segfault in a debug build?

Last thing I see before the segfault is related to profiles, so this may be related to #142.

**Comment by dpanter** [comment]
If I knew how to do that, sure. :)

Additional info:
Version 3.21 does run with Debian sid stock mesa 22.0.3-1, AMDVLK 2022.Q2.1 and AMDGPU-PRO Vulkan 21.50.2

**Comment by dpanter** [comment]
Additional info:
Version 3.21 segfaults with both ACO and LLVM using same Mesa-git 22.2 as first reported.

**Comment by dpanter** [comment]
AppImage version 3.11
![](https://i.imgur.com/80tJ9xQ.png)

**Comment by SaschaWillems** [comment]
Thanks for the confirmation. I did some debugging, and it looks like the profiles library sigegs for the llvmpipe device. See https://github.com/SaschaWillems/VulkanCapsViewer/issues/145

**Comment by dpanter** [comment]
A user replied to my bug report on Mesa gitlab, suggesting it could work when enabling the Khronos validation layer. For reference, it's Debian package: `vulkan-validationlayers` version 1.3.216.0-1 and env var: `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation`

Tested with 3.23, on my KDE Plasma Wayland system, the Wayland AppImage works and the X11 AppImage segfaults.
Current system specs, inxi -b -> https://termbin.com/qg8m

vulkancapsviewer_3.23_linux64_wayland.AppImage  log -> https://pastebin.com/YX3Sgw5S

vulkancapsviewer_3.23_linux64.AppImage log -> https://pastebin.com/6aD2isCy

**Comment by SaschaWillems** [comment]
I talked to that user on the Vulkan discord ;)

I still hope that MESA will fix this. Running with the validation layers isn't something that users should do when running the caps viewer.

**Comment by dpanter** [comment]
Closed my Mesa bugreport  as vulkancapsviewer now works with mesa-git 22.3.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6451

**Comment by SaschaWillems** [comment]
Thank you very much for the feedback on this. Glad to hear that the app is now working fine with MESA :)
