### ISSUE TITLE
Extension properties not shown for Google Pixel 7

### ISSUE THREAD

**Issue by per-mathisen-arm** [SaschaWillems/VulkanCapsViewer#150]
See http://vulkan.gpuinfo.org/displayreport.php?id=16769#properties_core_10 - the 'Extensions' tab is missing. Also missing in the app itself, so apparently not just a web front-end issue.

**Comment by SaschaWillems** [comment]
What version of the app? One of the latest releases sadly had a bug where extension properties weren't read at all, but the latest version https://vulkan.gpuinfo.org/download.php should fix this.

**Comment by per-mathisen-arm** [comment]
Version 3.24, the latest version available on Google Play Store.
