### ISSUE TITLE
deviceLUID read as uint8_t[VK_MAX_UUID]

### ISSUE THREAD

**Issue by qbojj** [SaschaWillems/VulkanCapsViewer#153]
Didn't look at source, but it formats LUID as UUID.
deviceLUID is uint8_t[VK_MAX_LUID] (VK_MAX_LUID == 8, VK_MAX_UUID == 16)

**Comment by SaschaWillems** [comment]
Can you elaborate? Is this in the client application or the database? And if it's in the client application is it a display problem or wrongly exported to the JSON?

**Comment by qbojj** [comment]
In the GUI app: ![image](https://user-images.githubusercontent.com/105227351/209548933-6aa1c36b-38b0-407b-bbdb-e3b1ad664226.png)
As you can see deviceLUID is in format 4-2-2-2-6 so it is formated as uint8_t[16].
