### ISSUE TITLE
Suggest show Device'Name(GPU Name) rather than Phone Name for Android Device on vulkan.gpuinfo.org.

### ISSUE THREAD

**Issue by vkensou** [SaschaWillems/VulkanCapsViewer#157]
On vulkan.gpuinfo.org, the website show devices. But these are phone's name not gpu's name. I think it is more helpful to display gpu's name. opengles.gpuinfo.org has same question.

![image](https://user-images.githubusercontent.com/9306197/203251458-582b3d19-3393-429a-abd9-eb2515fcf80f.png)

**Comment by SaschaWillems** [comment]
That's intentional and I don't want to change that (again). Displaying the GPU name for android devices has a lot of disadvantages and wouldn't be very meaningful. Unlike desktop, drivers come from the mobile device vendor and not the GPU vendor.
