### ISSUE TITLE
VK_EXT_extended_dynamic_state3 not dumped into profiles

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/VulkanCapsViewer#158]
The JSON file generated from  https://vulkan.gpuinfo.org/displayreport.php?id=16617 doesn't seem to have `VK_EXT_extended_dynamic_state3`

Maybe this is an issue due to not having an up-to-date Profile Library?

**Comment by SaschaWillems** [comment]
Yeah, I may need to update the profile files on the database side. Will take a look at it.

**Comment by SaschaWillems** [comment]
I have updated the profiles over at the database. Properties for `VK_EXT_extended_dynamic_state3` should now be included.
