### ISSUE TITLE
[Android] "unauthorized access to libcrypto.so"

### ISSUE THREAD

**Issue by 1ace** [SaschaWillems/VulkanCapsViewer#16]
[<img src="http://i.imgur.com/7nxM8Oh.png" height="192px" />](http://i.imgur.com/7nxM8Oh.png)

> Detected problems with app native libraries (please consult log for detail):
> libQt5Core.so: unauthorized access to libcrypto.so
> libQt5Core.so: unauthorized access to libssl.so

_(I don't have access to the logcat, unless I don't need to plug the USB cable to a computer anymore… Haven't done any Android dev in a few years :)_

From my quick googling, it looks like Qt5 is doing something [it shouldn't](http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#boringSSL):

> Android is moving away from OpenSSL to the BoringSSL library. If you’re using the Android NDK in your app, don't link against cryptographic libraries that are not a part of the NDK API, such as libcrypto.so and libssl.so. These libraries are not public APIs, and may change or break without notice across releases and devices.

I couldn't find anything on [Qt's bug tracker](https://bugreports.qt.io). If I find some time, I might file a bug over there.
I don't know if there's anything you can do, besides re-compiling with the latest Qt version when they fix it…

_As a side note, the UI of you app looks weird on my Nexus 5X running NDP2 (as you can see in the screenshot). I can open an issue with a better screenshot if you want to have a look, and I can test it for you :+1:_

**Comment by SaschaWillems** [comment]
Thx, I haven't tested the current build on my Shield yet, so I can't say anything about the crypto problems.

As for the UI I already have a screenshot from a mobile that also looks bad. Qt doesn't seem to adjust row heights to font size (on Android). But I can reproduce this with my shield, so no screenshot needed ;)

**Comment by m00head** [comment]
[QTBUG-54228](https://bugreports.qt.io/browse/QTBUG-54228) SSL not working on upcoming android N
> Richard Moore (qtnetwork) added a comment - 20/Jun/16 1:27 PM
> As you've noted, the developer must ship their own openssl (this is described in the documentation).

[QTBUG-52109](https://bugreports.qt.io/browse/QTBUG-52109) Starting with Android 6.0, google ditched openssl and switched to their own SSL implementation

[QTBUG-49069](https://bugreports.qt.io/browse/QTBUG-49069) SSL crash in Android 6 (Marshmallow)
> Eskil Abrahamsen Blomfeldt added a comment - 28/Oct/15 12:40 PM
> This is already in the documentation: http://doc.qt.io/qt-5/opensslsupport.html
> OpenSSL is not part of the Android NDK, so if you're using SSL and not bundling the libraries, you have no guarantees that it will work across devices or versions of Android.

**Comment by SaschaWillems** [comment]
@m00head: Thx for the information :+1: I don't have that much time to work on the caps viewer right now, but I'll see how and when I can fix this.

**Comment by SaschaWillems** [comment]
Just updated to a recent Qt Version (5.8) and with that this won't work at all and even normal http requests (not https) would crash, so the develop branch will now include prebuilt OpenSSL libraries.

**Comment by mabedMRD** [comment]
try to add openSSL manually to your project
https://github.com/ekke/android-openssl-qt

**Comment by SaschaWillems** [comment]
I already did. The issue is closed and the recent version uses manually built OpenSSL libraries.
