### ISSUE TITLE
VK_QUEUE_OPTICAL_FLOW_BIT_NV  is not shown corectly

### ISSUE THREAD

**Issue by qbojj** [SaschaWillems/VulkanCapsViewer#165]
in ui app VK_QUEUE_OPTICAL_FLOW_BIT_NV is printed as UNKNOWN_FLAG (0x100).

**Comment by SaschaWillems** [comment]
This will be fixed for the next release. Will take a look at the database too.

**Comment by SaschaWillems** [comment]
Fixed with release 3.29.
