### ISSUE TITLE
[Android] Profiles reporting in app interface vs uploaded report doesn't match

### ISSUE THREAD

**Issue by Leopard1907** [SaschaWillems/VulkanCapsViewer#172]
https://vulkan.gpuinfo.org/displayreport.php?id=15439#profiles

`VP_ANDROID_baseline_2021` gets reported as `False` but in Android app same profile gets reported as `True`.

Android app version: 3.29

**Comment by SaschaWillems** [comment]
Can you elaborate? Did you try to update the report?
