### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by Dominiquini** [SaschaWillems/VulkanCapsViewer#193]
When I tried running the application, it instantly crashed!

[Report.wer.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/13206304/Report.wer.txt)

OS Info: Windows 10 x64
APP Version: 3.32 x64
CPU Info: Intel i7-6700K
GPU Info: GTX 1060 6GBs
NVIDIA Driver: 545.92

Thanks

**Comment by Dominiquini** [comment]
I tested here the 32 bit version of the app and it works!
But my PC is 64 bits! It should work with the 64 bit version of the app!

Thanks.

**Comment by SaschaWillems** [comment]
Can you please disable all implicit layers and test again? I see some that may cause problems, e.g. AgaueEye or RivaTuner. Some of these layers are known to be faulty.

**Comment by Dominiquini** [comment]
I uninstalled AgaueEye and it's working now!

Thanks
