### ISSUE TITLE
Driver version conversion

### ISSUE THREAD

**Issue by SaschaWillems** [SaschaWillems/VulkanCapsViewer#2]
Driver versions are currently converted with the same convention as the Vulkan versions, which may yield wrong results depending on vendor.

**Comment by rdb** [comment]
For the NVIDIA driver, it seems that the minor driver version starts at bit 14, not bit 12.  This means that your software formats 1493811200 as 356.156.0 instead of the correct version number for this driver, 356.39.

Could you please also display the original number that it was formatted from on the gpuinfo site (and the vendor ID as well)?  This would make the online database more useful to me.

Alternatively, is there a way to download the raw dataset?

**Comment by rdb** [comment]
For completeness' sake I'll mention that the full formula that seems to work for NVIDIA driver versions is:

    major: (driverVersion >> 22) & 0x3ff
    minor: (driverVersion >> 14) & 0x0ff
    patch: (driverVersion >>  6) & 0x0ff

**Comment by SaschaWillems** [comment]
> For the NVIDIA driver, it seems that the minor driver version starts at bit 14, not bit 12. This means that your software formats 1493811200 as 356.156.0 instead of the correct version number for this driver, 356.39. The patch version starts at bit 6.

I've been in touch with NVIDIA on this. They already sent me a detailed explanation of their versioning scheme. I guess I'll have to convert differently depending on vendor ID in the future.

> Could you please also display the original number that it was formatted from on the gpuinfo site (and the vendor ID as well)? This would help me to figure out how the versions are formatted and make the database more useful to me.

The original version number is not yet stored in the db, only the converted string. But I'll change that. Vendor ID is there, so displaying is an option.

> Alternatively, is there a way to download the raw dataset?
Yes, but not public. There will be an URL in the near future that allows you to get a complete report as JSON. I'll make this public once the biggest problems and bugs (like this one) have been ironed out.

**Comment by rdb** [comment]
Many thanks!

Would you be willing to share the NVIDIA version information or is it not different from what I've already discovered?

**Comment by SaschaWillems** [comment]
Almost.

This is the information I got from NVIDIA :

	Starting with MSB :
	10 bits = major version (up to r1023)
	8 bits = minor version (up to 255)
	8 bits = secondary branch version/build version (up to 255)
	6 bits = tertiary branch/build version (up to 63)
