### ISSUE TITLE
Database sorting of API versions is incorrect

### ISSUE THREAD

**Issue by NicolBolas** [SaschaWillems/VulkanCapsViewer#20]
If you sort by API version, it turns out that 1.0.11 is considered to be *less* than 1.0.8. I assume you're just doing a basic string sort rather than a numeric sorting algorithm.

**Comment by SaschaWillems** [comment]
Thx. I'm not sorting manually. The online database uses [datatables](https://datatables.net/) which also does the sorting.

I'll check if I can easily fix this using datatables.

**Comment by SaschaWillems** [comment]
Fixed, see https://github.com/SaschaWillems/vulkan.gpuinfo.org/commit/f2e401d272d8c7a8d4cc379366562dce0316296c
