### ISSUE TITLE
Unable to submit with headerversion

### ISSUE THREAD

**Issue by openforeveryone** [SaschaWillems/VulkanCapsViewer#21]
I was not able to upload an entry today as the server did not accept the "headerversion" field.

I was able to submit it by commenting out line 255 of vulkanDeviceInfo.hpp
`properties["headerversion"] = std::to_string(VK_HEADER_VERSION);`
The submitted item is now at http://vulkan.gpuinfo.org/displayreport.php?id=409

The data that was refused can be seen here:
https://gist.github.com/openforeveryone/7577aaa3272f9e0054a34fd1215788cb

**Comment by SaschaWillems** [comment]
It seems that this field was introduced with one of the pull requests and missing on the database, so it fails to insert the reprort.

Thx for thint, I'll take a look at it later this week.

**Comment by m00head** [comment]
https://github.com/SaschaWillems/VulkanCapsViewer/pull/12#issuecomment-200962545

**Comment by SaschaWillems** [comment]
The missing field has since been added to the database, so uploading with a version build from sources should work fine.
