### ISSUE TITLE
Surface issues on macOS and iOS

### ISSUE THREAD

**Issue by richard-lunarg** [SaschaWillems/VulkanCapsViewer#212]
On macOS and iOS, when the "Surface" tab is selected the display area just shows "Could not get a valid surface, no surface information available!".

Also, the Queue families tab, shows 'false' for all Queue families "Supports Presentation".

I've took a quick look at the code and think I can correct these myself and will contribute a PR sometime in the next couple of weeks. Just recording it here in case someone else is already looking at this, or comes along to report it in the next couple weeks.

**Comment by SaschaWillems** [comment]
I don't have any Apple devices to test this on, so a PR would be very much appreciated :)

**Comment by richard-lunarg** [comment]
This PR does the trick on both desktop and mobile devices.

https://github.com/SaschaWillems/VulkanCapsViewer/pull/214

**Comment by richard-lunarg** [comment]
PR merged and this is fixed.
