### ISSUE TITLE
Select device, my NVIDIA graphics card cannot be displayed

### ISSUE THREAD

**Issue by suwei999** [SaschaWillems/VulkanCapsViewer#220]
Select device, my NVIDIA graphics card cannot be displayed
![1182_1730892082_hd](https://github.com/user-attachments/assets/e42a7a3d-a96d-4ce9-ab2b-f5b2363d63c1)

**Comment by SaschaWillems** [comment]
The screencap is very low-res and nigh impossible to read.

Please add some minimum information: What OS? What GPU? What driver version? Is this an integrated GPU?  etc.

**Comment by suwei999** [comment]
How do I install this software on the ubuntu 22.04 x86_64 operating system?

**Comment by suwei999** [comment]
I have solved this problem, thanks
![Uploading 选区_001.png…]()

**Comment by suwei999** [comment]
![Uploading 选区_001.png…]()
