### ISSUE TITLE
Vulkan caps viewer doesnt start

### ISSUE THREAD

**Issue by edoantonioco** [SaschaWillems/VulkanCapsViewer#23]
Time ago this worked as expected but now its not working. This on intel haswell (hd 4600). I use manjaro, and I already have all the vulkan-related packages installed. This is the terminal output:

> 
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> Violación de segmento (`core' generado)
>

**Comment by SaschaWillems** [comment]
Can you debug? The libpng warnings are fine (caused by Qt). Do other Vulkan applications work?

**Comment by edoantonioco** [comment]
True, I just copied all the output without taking a look if it was relevant. Related to other vulkan applications, on vkcube the output is also 

> Violación de segmento (`core' generado)

and not sure which other vulkan demo I can use. Overall I dont expect vulkan apps to work on haswell (like the talos principle wich has never worked), but this one worked before, so thats strange. Related to debug (with qt or qtcreator) I dont have experience, but I can take a look at it.

**Comment by HighIO** [comment]
@edoantonioco You may install the driver like 'vulkan-intel'
