### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by TotalCaesar659** [SaschaWillems/VulkanCapsViewer#25]
Hello! Could you make translation support for VulkanCapsViewer?
I can make some translations to another languages if this support will be created.

**Comment by SaschaWillems** [comment]
I don't have any plans for a translation support atm. There's not much text in the Vulkan Caps Viewer aside from the terms used by the Vulkan API.

**Comment by TotalCaesar659** [comment]
OK, but it's more comfortable for many people to use programs in their native language. So it'll never be redundant.
