### ISSUE TITLE
AMD maxImageExtent for surface depends on window size

### ISSUE THREAD

**Issue by zao** [SaschaWillems/VulkanCapsViewer#27]
In reports such as my http://vulkan.gpuinfo.org/displayreport.php?id=923#surface, cards like AMD RX 470 list a `maxImageExtent` of `927x755`.

This very odd extent is the same size as the client area of the VulkanCapsViewer HWND, which is used by the code to construct the surface used to query this information.

**Comment by SaschaWillems** [comment]
Other devices also seem to report the client area of the window instead, so this may be a driver issued

The spec is now 100% clear on this:

> maxImageExtent contains the largest valid swapchain extent for the surface on the specified device.

So I may open up an issue to clarify what it actually reports.

**Comment by krOoze** [comment]
The report seems invalid. `minImageExtent` and `maxImageExtent` must be equal to `currentImageExtent` on `VK_KHR_win32_surface`. I suggest just removing those values too from that platform.
