### ISSUE TITLE
It's not working on Wayland on Linux on Kwin (Plasma 5)

### ISSUE THREAD

**Issue by edoantonioco** [SaschaWillems/VulkanCapsViewer#28]
If I try to use the program on wayland, it just doesnt doesnt work at all.

On the terminal output, this is what difer compared to run it on xorg: 

> QObject::connect: invalid null parameter

**Comment by SaschaWillems** [comment]
There's no support for Wayland yet. I'm not sure about Qt, but at least on the Vulkan side of things there's only support for XCB (on Linux right now).

I'll take a look at this, though I'm pretty sure that this will end up as a separate build configuration.

**Comment by SaschaWillems** [comment]
Wayland support has been added some time ago, so this should work fine now.
