### ISSUE TITLE
Headless support?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [SaschaWillems/VulkanCapsViewer#29]
Hi,

I am quite surprised as everybody is pointing to different issues but nobody is asking for a Headless version. So, how difficult would be to generate a report that either goes directly to STDOUT or at max an HTML report dump file?

Thank you in advance,
Julian

**Comment by SaschaWillems** [comment]
Headless has been requested by several IHVs and it's on my internal todo list (no ETA yet). It will output the json report file to disk.

**Comment by julianxhokaxhiu** [comment]
Nice, looking forward to it. Thank you.

**Comment by SaschaWillems** [comment]
The next release allows you to output the report as json to disk without having to start the UI.

**Comment by julianxhokaxhiu** [comment]
Veeery nice! Thank you :D
