### ISSUE TITLE
It's not detecting RX 460 with mesa drivers correctly.

### ISSUE THREAD

**Issue by lucitribal** [SaschaWillems/VulkanCapsViewer#34]
It displays as AMD RADV POLARIS11 with deviceid 26607 
I'm using Ubuntu 17.04 Mate and use the Mesa 17.03 driver.

**Comment by SaschaWillems** [comment]
The caps viewer displays exactly what it get's from the driver via the Vulkan API, so if the deviceid (or anything else) is reported wrong then it's probably a driver related problem and nothing I can fix.

**Comment by lucitribal** [comment]
Thanks for the quick reply. It looks like the issue is with either mesa or vulkan. I'll test if updating to a newer version fixes it.

**Comment by SaschaWillems** [comment]
Any news on this?

**Comment by grmat** [comment]
I don't see something wrong here. RX 460 *is* Polaris 11, the device ID is correct (0x67EF) and the Mesa Vulkan driver is called radv.
