### ISSUE TITLE
Very inconsistent results

### ISSUE THREAD

**Issue by startas** [SaschaWillems/VulkanCapsViewer#40]
Are nvidia vulkan drivers unstable or what is going on ? I checked the website, and results dont make any sense - older nvidia driver versions are showing newer vulkan version support for the same graphic card and so on.

**Comment by SaschaWillems** [comment]
NVIDIA offers [two drivers ](https://developer.nvidia.com/vulkan-driver) branches that support Vulkan. The developer driver may come with a lower driver version but may support a higher Vulkan API level. I guess that's why you see reports with a lower driver but higher API version.

**Comment by startas** [comment]
Yes, that could be it.
