### ISSUE TITLE
New binary release with VK_EXT_conservative_rasterization support of waiting for Vulkan next..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/VulkanCapsViewer#41]
Hi,
I see you have commits with conser. raster support but no new binary releases..
just wanted to see how support is on Nvidia dev drivers optinal caps of this extensions..
maybe your are waiting for possible "Vulkan 2.0" on GDC 2018 with more exts/features and then do a new binary release..
anyway can wait..
just asking..
keep up the good work..

**Comment by SaschaWillems** [comment]
I've been pushing regular updates trying to support extensions as early as possible, so closing this.
