### ISSUE TITLE
Issue submitting results from an experimental Android x86 ISO with Vulkan support..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/VulkanCapsViewer#42]
Hi,
since a week approx. @maurossi provides Android x86 experimental ISOs with Vulkan support..
these are for Oreo 8.1:
https://drive.google.com/drive/folders/0B_OFHiIqgpSFTFpkQWc1eXV3ME0
and also as today one for Nougat:
https://drive.google.com/drive/folders/0B_OFHiIqgpSFMlk4bkhaMnAwbDA
note that seems Vulkan has no ICD today for Android and driver is hardcoded and set in property in ro.hardware.vulkan..
so with every ISO can test only one GPU vendor..
so Mauro has provided Oreo ones hardcoded to use ANVIL Intel HD graphics and Nougat to use RADV for AMD cards..
I have a PC with Vega and Intel HD 530 graphics so can test both..
here a captures running on Vega (showing I don't lie :-) ):

(please open it in separate window to not see up to down)..

![img_1946](https://user-images.githubusercontent.com/669305/36406471-65de3f30-15f7-11e8-84f4-f792d56590fd.JPG)
![img_1945](https://user-images.githubusercontent.com/669305/36406472-65f5d686-15f7-11e8-881d-6d7006f817b8.JPG)

really the Vulkan support with these ISOs is very early.. any app that creates a swapchain I believe doesn't work correctly..
anyway as you see your apps seems to work correctly (I downloaded your x86 apk from your site as first I downloaded from Play store and seen some HOUDINI things via logcat so assumed Play Store app is only for ARM)..

was trying to submit a report for future reference.. but says an error saying something about parsing/reading extension list.. altough as you can see device extensions list seems normal with no strange characters and the like..

could explore the app being open source but maybe you can provide a clue and perhaps help catch bug in the Vulkan support on these ISOs..
thanks..

**Comment by SaschaWillems** [comment]
Can you save the report and upload it somewhere so I can check why it fails uploading?

**Comment by oscarbg** [comment]
How I’m supposed to do that? Seems Android app can’t save report locally as json file..

**Comment by SaschaWillems** [comment]
Sry, forgot that this is android. There was a save button in an older version, but Qt's save dialog never really worked on Android so I removed it.

But I just added some error logging to the server-side report upload script. Can you try uploading again? If it fails (again) with that exact error message I'll get all the required details via mail.

**Comment by oscarbg** [comment]
Ok,
sended 2 times..
sorry for lag..
as Vega doesn't worked on Nougat build, have to enable IGPU in BIOS, reflash the Oreo ISO on the USB media with Oreo and throw ethernet cable across the home as my wifi isn't supported..
hope you don't need another try..
keep me informed please of your findings..

**Comment by SaschaWillems** [comment]
Thx, got both reports in the mail along with the SQL error. 👍 

The upload fails because the report contains duplicate extensions. ```VK_KHR_incremental_present``` is listed twice and this violates the primary key rule for the per-report extension table.

I could change the upload script to skip duplicate extensions, though it may also be good idea to tell the driver creator that extensions shouldn't be listed twice.

**Comment by oscarbg** [comment]
thanks @SaschaWillems..
the strange thing is, you know, after all is well known Mesa ANVIL driver compiled for Android,
I will point to @maurossi in case he doesn't follow this thread.. if nothing obvious he can see then yes seems a issue for Mesa-devel..

**Comment by baryluk** [comment]
For reference here are reports for the same device on Linux (looks like all of them are for x86_64):

https://vulkan.gpuinfo.org/listreports.php?devicename=Intel(R)%20HD%20Graphics%20530%20(Skylake%20GT2)&platform=linux

Oldest one is from Mesa 17.2, and newest from Mesa 20.0-rc1 (from you @oscarbg :D). 

https://vulkan.gpuinfo.org/displayreport.php?id=7291

Really strange about the duplicate extension listed. Maybe some Vulkan layer is messing something up?
