### ISSUE TITLE
Intel Windows drivers keep getting new extensions but due to not changing apiVersion or DriverVersion can't submit reports..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/VulkanCapsViewer#43]
As said i checked 4958 driver and has two new extensions vs posted driver:
conservative raster and sample locations..
would be nice if server or program checks that there are new extensions vs existing in database and allow reuploading..
Proof of is a report:

[Intel(R) HD Graphics 5304958.zip](https://github.com/SaschaWillems/VulkanCapsViewer/files/1742564/Intel.R.HD.Graphics.5304958.zip)

**Comment by SaschaWillems** [comment]
Sad to see that some vendors still won't update their driver versions. If device id, driver **and** api version stay the same across multiple driver releases it's pretty hard creating a mechanism to allow uploading those reports. I'll try to ping someone at Intel, though Vulkan on Windows is pretty low priority for them.

**Comment by oscarbg** [comment]
Hi,
"Vulkan on Windows is pretty low priority for them"
I wouldn't say so at least juding from extension support list.. note conservative raster isn't even on AMD GPUs and on Nvidia is a developer driver only..
also I successfully tested Wolfenstein II (Vulkan game) say a month after launch and it worked with latest drivers altough I believe  Intel HD igPUs are not listed as supported GPUs of that game ( it rendered almost correctly)..
note seeing Platform:Windows label I also forgot to say this problem is also present on Linux.. 
Mesa dev builds where for example in between of their quarterly stable releases (say 17.3,18.0,18.1)  they keep same driver version (right now 18.0.99 will stay for approx. three months..) and if they  implement some new extension and they don't change api version which is pretty common also I'm not able to send report..
anyway I think you can get that problem fixed without Intel support:
on Windows a solution is to check reported Windows driver version from Windows directly:

`{//D3DADAPTER_IDENTIFIER9

			IDirect3D9Ex* g_pD3D = nullptr;
			D3DADAPTER_IDENTIFIER9* d3dai = new D3DADAPTER_IDENTIFIER9{};
		
			//Create Direct3D9Ex interface and query the primary adapter

			if (FAILED(hr=Direct3DCreate9Ex(D3D_SDK_VERSION, &g_pD3D)))
				errorfailedto(hr, "create Direct3D 9 interface");
			else
			{ 
				if (FAILED(hr=g_pD3D->GetAdapterIdentifier(D3DADAPTER_DEFAULT, 0, d3dai)))
					errorfailedto(hr, "get adapter identifier");
				else
					printf("%s : %i.%i.%i.%i\n", "Video driver version",
						HIWORD(d3dai->DriverVersion.HighPart), LOWORD(d3dai->DriverVersion.HighPart), HIWORD(d3dai->DriverVersion.LowPart), LOWORD(d3dai->DriverVersion.LowPart) );
			}
			g_pD3D->Release();
`
of course this is simple code and one drawback is multiple gpus on system must check vendor to truly know what version is associated with what vendor (well at least we have the luck all GPUs from same vendor must have installed same vendor driver version)..

if you want to support Linux Mesa case also seems better is in server altough all three versions are the same  check device extension list  and if different allow submit..
of course as this could become more than one submission as for example Intel case should allow two submissions once when eneable sample loc. and another driver enable conser. raster, so server should check list of all reports matching equal three versions..
of course I'm not asking you to implement any of these... as is not critical.. just saying..
thanks..

**Comment by SaschaWillems** [comment]
This should be covered by the recently introduced update mechanic, that also checks if the report's extension listing differs from the one in the database and then lets you update that report.
