### ISSUE TITLE
Modifications for building on Ubuntu 18.04 bionic-dev with Qt5.9..

### ISSUE THREAD

**Issue by oscarbg** [SaschaWillems/VulkanCapsViewer#44]
Ok,
just build it too see new extensions info you worked few days ago..
on Ubuntu 18.04 with *included* qt5.9 in bionic repos is strange but your code seems qt4 compatible and qt5 incompatible in same ways:

just to fix it require:
change QtGUI/.. to QtWidgets in following ui_vulkankcapsviewer.h:

#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QTreeView>
#include <QtWidgets/QTreeWidget>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

remove/replace , QApplication::UnicodeUTF8 with /* , QApplication::UnicodeUTF8*/
now compiles OK..

**Comment by oscarbg** [comment]
notice I builded on Windows also with Qt 5.10.1 and 5.11alpha and no changes needed so seems to be specific to included Qt on Ubuntu repos..

**Comment by SaschaWillems** [comment]
Thx, I'll look into this. I currently build with QT 5.8 and some older Linux distros might still come with older Qt libraries, so I'll have to check not to break compatibility (happened a few times).

**Comment by oscarbg** [comment]
seems with latest bionic qt changes, this changes aren't needed..
 so closing..
