### ISSUE TITLE
Error at platform details when trying to upload report

### ISSUE THREAD

**Issue by m00head** [SaschaWillems/VulkanCapsViewer#46]
![screenshot_20180307-170606](https://user-images.githubusercontent.com/3127906/37106694-5fee08aa-222a-11e8-80fc-b4e5a7e2652b.png)

**Comment by SaschaWillems** [comment]
Please add some details. Is this from running an official build?

**Comment by m00head** [comment]
Yes, this with the official build version 1.4 downloaded from the Play Store.

I have tried clearing the data/cache and reinstalling the app, but I still get the same error.

**Comment by SaschaWillems** [comment]
Please try to submit again. I haven't found (or fixed) the problem but I have enabled some error reporting, so if your upload now fails I'll get a complete copy of the actual report you tried to upload so I can check what's going wrong here.

**Comment by SaschaWillems** [comment]
Can you please try to upload again? It looks like this was caused by a trigger that gets the device retail brand name from google's official device list and for some devices there are multiple entries in that list. I have fixed that trigger, so uploads should work again for such devices.

**Comment by m00head** [comment]
Tried uploading again as requested and it worked.

Closing issue as resolved.
