### ISSUE TITLE
Linker error on Linux  /usr/bin/ld: cannot find -lvulkan-1

### ISSUE THREAD

**Issue by timjp87** [SaschaWillems/VulkanCapsViewer#5]
Hi,

I cloned the repo on Arch Linux and made a build directory inside of it. I entered the build directory and ran `cmake ..` to generate the Unix Makefiles. However, when running `make` it fails at the linker step with the error in the title. 

I had to go into CMakeFiles/vulkancapsviewer.dir/link.txt and change -lvulkan-1 to -lvulkan to get it to build the vulkancapsviewer binary. I have the vulkan loader installed aswell as the NVIDIA 355.00.26 driver with its ICD manifest in /etc/vulkan/icd.d/nvidia_icd.json and the vulkan header files form the official Arch Linux package. 

I'm not familiar with the inner workings of cmake and how it tries to figure out the link commands. Is that something that can be fixed in the codebase of this repo?

**Comment by SaschaWillems** [comment]
I have moved to project to a QtCreator project, which is the preferred way of building. 

The CMakeLists.txt is propably out of date. I'll take a look at this.
