### ISSUE TITLE
Vulkan API headers 1.1.95

### ISSUE THREAD

**Issue by elviras9t** [SaschaWillems/VulkanCapsViewer#56]
I would like to ask for support for Vulkan API 1.1.95, and I am writing this for several reasons...
- In reports already has `VK_KHR_shader_float16_int8` and `VK_KHR_shader_float_controls` (0% supported), so want to ask just add support of reporting about support float16 and int8 by these extensions
- NVIDIA recently released Vulkan API beta driver with these extensions support 
- We doesn't want to sending report without that information (reports can't be overridden)

**Comment by SaschaWillems** [comment]
I'll try to release an updated version this weekend.

But note that I only work on this in my spare time, and as such the caps viewer may lag behind from time to time.

I also plan on adding some way for updating existing reports, but I don't think this will happen in 2018.

**Comment by SaschaWillems** [comment]
Updated versions are now available on all supported platforms, see https://vulkan.gpuinfo.org/download.php
