### ISSUE TITLE
boringssl libcrypto and libssl

### ISSUE THREAD

**Issue by nagesh1044** [SaschaWillems/VulkanCapsViewer#59]
How to build libcrypto.so and libssl.so for Android x86 using boringssl?. If any one is having static libs please share with us. It is very helpful

**Comment by nagesh1044** [comment]
Thanks for the update. But for NDK support google is not allowing to use OpenSSL. Goolge was changed to BoringSSL.

https://www.zdnet.com/article/google-takes-openssl-and-turns-it-into-boringssl/

Have a look.

**Comment by SaschaWillems** [comment]
That's not true. OpenSSL still works, and afaik BoringSSL won't properly work with Qt apps. 

The current version of the caps viewer available in the store also uses OpenSSL, works fine and there was nothing preventing me from releasing it to the playstore.
