### ISSUE TITLE
How to send KeyEvent/Pointer Event from One Device to another Device using Socket..  Like Teamviewer quick support

### ISSUE THREAD

**Issue by nagesh1044** [SaschaWillems/VulkanCapsViewer#60]

**Comment by SaschaWillems** [comment]
Please do me a favor and at least add some minimal information, otherwise I have no chance of knowing what you actually asking for. The description sounds like something that has got nothing to do with the caps viewer.

**Comment by SaschaWillems** [comment]
I don't see how this is connected to this project. This sounds more like a general question that should be asked elsewhere.
