### ISSUE TITLE
combinedImageSamplerDescriptorCount is 0

### ISSUE THREAD

**Issue by sfricke-samsung** [SaschaWillems/VulkanCapsViewer#61]
The `combinedImageSamplerDescriptorCount` value in the Extended -> Properties for `VK_KHR_sampler_ycbcr_conversion` seems to be 0 for everyone. This is a per-format property and curious if this is a bug as the spec says

> combinedImageSamplerDescriptorCount is the number of combined image sampler descriptors that the implementation uses to access the format.

**Comment by SaschaWillems** [comment]
You're right. It's actually a per-format property and reading it the way the CapsViewer does is obviously wrong. Will fix this with the next update.

**Comment by SaschaWillems** [comment]
The next release (2.00) will have all C++ code for fetching extension and property info generated from the Vulkan api spec xml, which will also fix this one ;)
