### ISSUE TITLE
vulkan.gpuinfo.org hasn't been updated with 1.93

### ISSUE THREAD

**Issue by 1ace** [SaschaWillems/VulkanCapsViewer#68]
http://vulkan.gpuinfo.org/download.php still shows 1.92 as the latest :wink:

**Comment by SaschaWillems** [comment]
That's correct. I haven't had time to release the app to all platforms yet.

**Comment by SaschaWillems** [comment]
Updates for all platforms are now online. I also pushed a new Android version to the play store.
