### ISSUE TITLE
Missing information about platform-dependant surface extensions

### ISSUE THREAD

**Issue by Jajcus** [SaschaWillems/VulkanCapsViewer#7]
It would be great to see what presentation platform can a driver handle. I mean the `VK_KHR_*_surface` extensions.

For PC Linux it might be one or more of: VK_KHR_wayland_surface, VK_KHR_xcb_surface, VK_KHR_xlib_surface. Android and Windows are easier cases here.

I know these are tricky to probe, as those are instance extensions announced by the loader, but might be supported or not by a driver. There are `vkGetPhysicalDevice*PresentationSupportKHR()` and `vkGetPhysicalDeviceWaylandPresentationSupportKHR()` functions, but they all need some initialization for the given platform (like a connection to the display server or compositor).

Additionally information about supported surface capabilities could be collected.

**Comment by SaschaWillems** [comment]
I have just merged the surface_caps branch into master and added all the things required to store surface properties to the database (see [this report for example](http://vulkan.gpuinfo.org/displayreport.php?id=843#surface)).

On Windows and Android this is pretty easy, but on Linux it's XCB only right now. I'll take a look at how to add the other ones like Wayland in the future.

I'll also try to put updated Versions of the caps viewer online some time this weekend.
