### ISSUE TITLE
No dependencies for Linux

### ISSUE THREAD

**Issue by tichun** [SaschaWillems/VulkanCapsViewer#72]
> ./vulkanCapsViewer: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./vulkanCapsViewer)

Libraries are not shipped with the executable so program won't run on Ubuntu 18.04 (qt 5.9)
Under Windows you are shipping libraries alongside the executable so there is no problem.

**Comment by SaschaWillems** [comment]
Deploying in Linux is a lot harder than on Windows, but it seems that appimage might be the easiest/best way.

Can you please try with this version: http://vulkan.graphics/downloads/Vulkan_Caps_Viewer_2_00-x86_64.AppImage.tar.gz

This is an appimage version of the caps viewer that should include all dependencies required to run it.

I have tested on two different major Ubuntu versions, and both worked fine.

If this works then it'll be the future way of releasing versions for Linux.

**Comment by mercuriete** [comment]
I am a Gentoo user and it works for me.
Nice to see a new way to distribute apps.

**Comment by SaschaWillems** [comment]
Thanks for the feedback :)
