### ISSUE TITLE
(windows) Crashes with `gfx-portability-icd` and `swiftshader-icd` registered

### ISSUE THREAD

**Issue by Hugobros3** [SaschaWillems/VulkanCapsViewer#76]
Pretty self-explanatory, both the latest build of vulkanCapsViewer and the last Vulkan 1.0 only builds ( 1.4 ) refuse to start on Windows 10 x64, experiencing a segfault, if either the ICD for `gfx-portability` ( subset of Vulkan on top of DX12 and other APIs) or `swiftshader` ( CPU-only software implementation ) ICD's are present.

I registered those in `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers`, `vulkaninfo` sees them just fine. Removing them (or setting the dword value for them to something different than 0 ) allows vulkancapsviewer to proceed as normal and display the gui.

I build both those from source this week so reproducing should just be a matter of cloning them and registering their ICDs.

**Comment by Hugobros3** [comment]
[For good measure, here is my vulkaninfo output with both ICDs registered](https://pastebin.com/pGRkM8cU)

**Comment by SaschaWillems** [comment]
How do I register e.g. swiftshader as an ICD to test this?

**Comment by SaschaWillems** [comment]
How do I register swiftshader as a valid ICD? The loader has a list of known device, and refuses to load the swiftshader ICD for me.

**Comment by Hugobros3** [comment]
On Windows you go through the registry: 

I added a DWORD key in `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers` named 
`C:\Users\Gobrosse\git\swiftshader\out\build\x64-Release\Windows\vk_swiftshader_icd.json`.

The key has to have value zero, otherwise it's ignored. This is following the official vulkan loader documentation.

**Comment by SaschaWillems** [comment]
Been there done that ;) But at least a current loader will disable that driver because it's not a known icd, see https://github.com/KhronosGroup/Vulkan-Loader/blob/80e9b24ff8e536427b7e99bc0f07792bc9647d10/loader/loader.c#L818. Are you using an older loader?

**Comment by Hugobros3** [comment]
I have SDK 1.1.101 installed, that sounds like a very restrictive change on the part of the loader indeed 🤔 Not sure how things would work out for projects such as swiftshader, they don't have a "device" to put these keys in...

**Comment by SaschaWillems** [comment]
Seems like it was recently introduced. I have [opened an Issue](https://github.com/KhronosGroup/Vulkan-Loader/issues/270) on this over at the loader repo.

The change also queries DXGI to see if a device for a vendor is present, so it's not even possible to just rename the swiftshader ICD to something else.

Once this is resolved I'll check how to make the caps viewer work with swiftshader.

**Comment by Hugobros3** [comment]
[The docs for the loader](https://vulkan.lunarg.com/doc/sdk/1.1.121.2/windows/loader_and_layer_interface.html) mention you can use an environment variable (`VK_ICD_FILENAMES`) to override the ICD search path

`set VK_ICD_FILENAMES=\windows\system32\nv-vk64.json`

**Comment by SaschaWillems** [comment]
That one works. Thanks.

And it looks like it's crashing because swiftshader isn't exporting ```vkGetPhysicalDeviceWin32PresentationSupportKHR```.

I'll take a look at how to work around this.

**Comment by Hugobros3** [comment]
Both Swiftshader and gfx-portability are in early stages anyway and aren't too usable yet, but it would be really nice exposure and a cool way to track their progress to have them listed on the vulkan.gpuinfo.org DB. If VulkanCapsViewer can't support them right now it's not a big deal, this issue will just track that progress.

**Comment by SaschaWillems** [comment]
Swiftshader is already able to run most of my samples, and it looks like it's really only about that single function not being exported. Not sure how to handle that yet though.

**Comment by SaschaWillems** [comment]
My patch for swiftshader got approved. If you built again from the current source, you should be able to use it with the caps viewer.

gfx-portability crashes with the same error at ```vkGetPhysicalDeviceWin32PresentationSupportKHR```. I'll also submit a patch for that.

**Comment by Hugobros3** [comment]
[Works fine, thanks!](http://vulkan.gpuinfo.org/displayreport.php?id=7139) :)

Will look into fixing portability too one of those days, it's still quite incomplete in it's DX12 backend ( no descriptor set support if i'm correct, which is obviously quite limiting )

**Comment by SaschaWillems** [comment]
Not necessary. I already have it up-and-running with gfx-portability and will submit a patch asap ;)

**Comment by Hugobros3** [comment]
Could you handle "VK_PHYSICAL_DEVICE_TYPE_CPU" ? The report shows up as "unknown device" on the site

**Comment by SaschaWillems** [comment]
My patch for gfx-portability was also merged: https://github.com/gfx-rs/portability/commit/a9edbc0337b2b73c5af60b777ae80f7654799b7f

Will also add device_type_cpu in the next update.
