### ISSUE TITLE
lineWidthGranularity in web is just 0 while in program it is 0.0625

### ISSUE THREAD

**Issue by ValZapod** [SaschaWillems/VulkanCapsViewer#77]
https://vulkan.gpuinfo.org/compare.php?compare=compare&id%5B7122%5D=on&id%5B6983%5D=on
![image](https://user-images.githubusercontent.com/31514790/67384193-608a7980-f599-11e9-893e-d52d8cbafb68.png)

**Comment by SaschaWillems** [comment]
Haven't had time to take a look at it. May take a few days, but I'll check if it's an actual data error or just a display problem.

**Comment by SaschaWillems** [comment]
Looks like this is just a display problem, with the compare functionality wrongly rounding that volume. Will fix that with the next update of the database front-end.

**Comment by ValZapod** [comment]
@SaschaWillems Cool. BTW, this number changed in latest nvidia driver (440.97). Is it something important, i.e. why they changed it?

**Comment by ValZapod** [comment]
@SaschaWillems BTW, https://vulkan.gpuinfo.org/displaydevicelimit.php?name=lineWidthGranularity so the problem is not in that part.

**Comment by SaschaWillems** [comment]
This has just been fixed.

**Comment by ValZapod** [comment]
Nice! So what is this variable doing?
