### ISSUE TITLE
Feature request: Using Vulkan hardware caps viewer in command line?

### ISSUE THREAD

**Issue by Groovounet** [SaschaWillems/VulkanCapsViewer#90]
Hi Sascha!

Looking at the main.cpp file I could see there is some command line support and end up with this:
![image](https://user-images.githubusercontent.com/367227/78905047-b1295c80-7a7d-11ea-8a32-e0f8931be53b.png)

I could use more commands to
- Submit my report to your webside
- Look for my device on the website
- Open the database Website
- Save the json report

What do you think of this?

**Comment by SaschaWillems** [comment]
That sounds like a good idea, esp. the submit one. Will try to add these with upcoming versions.

**Comment by SaschaWillems** [comment]
There will be a light-weight command line only version with as little dependencies as possible, see #147
