### ISSUE TITLE
Windows release (un)zip version requirement.

### ISSUE THREAD

**Issue by eloj** [SaschaWillems/VulkanCapsViewer#92]
This is probably not something you care about, but I'll report it since I ran into it just now.

The Windows release (i.e `vulkancapsviewer_2_03_win64.zip`) seems to require a fairly competent 'unzipper'. `unzip` (6.00) as packaged on my Linux Mint or Debian machines can't handle it, which is perhaps not that bad, but neither seems the built-in zip support on Windows 10 (1909 and 2004).

On Windows I can open the archive and explore it, but actually trying to extract any file fails with "Error 0x80004005: Unspecified error".

![Image](https://i.imgur.com/PDnAv8w.png)

Unzip on linux reports:

```bash
$ unzip -x vulkancapsviewer_2_03_win64.zip 
Archive:  vulkancapsviewer_2_03_win64.zip
   skipping: vulkancapsviewer/Qt5Core.dll  need PK compat. v6.3 (can do v4.6)
```

As always for these sort of issues, the solution is to use 7zip.

**Comment by SaschaWillems** [comment]
Actually never noticed this as I've been using 7-zip like since forever. But having a zip for Windows that doesn't extract with the built-in unzipper isn't great, so I'll use the built-in zipper for the next release.

Thanks for bringing this up.

**Comment by eloj** [comment]
👍
