### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [SaschaWillems/VulkanCapsViewer#94]
Currently the AppImage is inside a tar.gz. This is not recommended due to the reasons explained at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake.

It would be very welcome if you could provide the "naked" AppImage for download. Thank you.

**Comment by SaschaWillems** [comment]
My main development platform is Windows, which I'm also using to upload the releases. I'm only packing the AppImage to keep the executable bit, that to my knowledge would get lost if uploading from a Windows machine.

If there is an easy way to avoid this, I'll upload the AppImage instead.

**Comment by probonopd** [comment]
All AppImage users know how to set the executable bit. This has nothing to do with uploading from a Windows machine, but is a security feature in Linux. There are optional tools that even can do it automatically.

**Comment by SaschaWillems** [comment]
I have replaced the archives with the AppImages, and will do that with all new releases.
